---
title: "Homework 2"
author: "Kyle Kim"
date: "2022-10-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(tidymodels)
library(yardstick)
abal <- read_csv(file = "/Users/kylekim/Desktop/homework-2/data/abalone.csv")
```

## Q1
```{r}
abal <- abal %>%
  mutate(age = rings + 1.5)
abal
```

```{r}
abal %>%
  ggplot(aes(x=age)) + geom_histogram()

## The graph is normally distributed, with the right skew being the longer end.
```

## Q2
```{r}
set.seed(1000)
splitdata <- abal %>% initial_split(prop = 0.8, strata = age)
abal_training <- training(splitdata)  # 80%, Tibble: 3,340 x 10
abal_testing  <- testing(splitdata)  # 20%, Tibble: 837 x 10
```

## Q3
```{r}
recipe <- recipe(age ~ ., abal_training) %>% 
  step_rm(rings) %>%  # Remove 'rings' because not a predictor of age
  step_dummy(all_nominal_predictors()) %>% # step 1
  step_interact(terms = ~ starts_with("type"):shucked_weight + longest_shell:diameter + shucked_weight:shell_weight) %>% # step 2
  step_normalize(all_predictors()) # step 3 & 4

recipe
```

## Q4
```{r}
lm <- linear_reg() %>% 
  set_engine("lm")
lm
```

## Q5
```{r}
wrkflow <- workflow() %>%
  add_model(lm) %>%
  add_recipe(recipe)

fitted_model <- fit(wrkflow, abal_training)
fitted_model
```

## Q6
```{r}
prediction <- tibble(type = 'F', longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1, rings = 0)

femaleabal <- predict(fitted_model, prediction)
femaleabal
# The predicted age of a female abalone is approximately 22.68 years.
```

## Q7
```{r}
mset <- metric_set(rsq, rmse, mae)

predvalue_tibble <- predict(fitted_model, abal_training) %>%
  bind_cols(abal_training %>% select(age))

mset(predvalue_tibble, age, .pred)

# Our R^2 value is low at approximately 0.562, meaning that approx. 56% of the 
# variability is explained by the model.
```

